services:
  wiki:
    image: ghcr.io/requarks/wiki:3.0.0-alpha
    container_name: wikijs_beta
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASS: ${ADMIN_PASS}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    restart: unless-stopped
    ports:
      - "3001:3000"

volumes:
  db-data: