---
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKER_MODS=linuxserver/mods:swag-auto-reload
      - TZ=Europe/Prague
      - URL=mkomanek.eu
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=matejkomanek@outlook.cz
      - CERTPROVIDER=zerossl
      - PROPAGATION=50
    volumes:
      - /SWAG:/config
    ports:
      - 443:443
      - 80:80
    restart: always
